server:
  port: 8091
spring:
  application:
    name: pixel-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
